### ISSUE TITLE
NPU load not showing

### ISSUE THREAD

**Issue by heymikid** [benhoff/rockchip-ncurse-monitor#1]
Hi,

I am running on an Orange Pi 5 Pro but the NPU load is not showing.
It is certainly showing in /sys/kernel/debug/rknpu/load
See the attached image (cat /sys/kernel/debu/rknpu/load on top, system monitor on the bottom):
![Screenshot 2024-12-19 171555](https://github.com/user-attachments/assets/f9ba53e0-c4fa-49db-91d3-de17529c7eae)

I tried to look into the source code and the regular expression looks right (the core_regex, what does the total_regex look for?)

If you have time, can you please look at it?

Thanks

**Comment by benhoff** [comment]
@heymikid , for sure I'll take a look. 

Code was thrown together pretty quickly with the help of chatgpt, which sometimes produces some brittle code.

probably what you're seeing now.

**Comment by benhoff** [comment]
@heymikid , you did run using `sudo` correct?

**Comment by heymikid** [comment]
I ran with sudo. And the upper dump was with root access to the file. 
 I was previously running this on an Orange Pi 4 (one NPU) and got the right result.
I am not familiar with the c++ regexp functions (it's been a while for me). I didn't see the comma "," in the regexp, but I convinced myself it is simply not required since it is searching how many times the regexp pattern appears in the string (which should match the 3 NPU's on that line), right? So I am not sure why it isn't picking this up.

**Comment by benhoff** [comment]
Something like the below would probably work, although I have not tested it at all.

Can you help me understand the multiple lines? Is each line a different thread?

So core 0 and core 1, each have 5 threads?


```
#include <fstream>
#include <regex>
#include <string>
#include <vector>

class SystemMonitor {
public:
    void readNpuLoad();

private:
    std::vector<int> npuLoad;
    size_t nrNPUs;
};

void SystemMonitor::readNpuLoad() {
    // Clear existing load data
    npuLoad.clear();

    // Open the NPU load file
    std::ifstream file("/sys/kernel/debug/rknpu/load");
    if (!file.is_open()) {
        // Handle file open failure if necessary
        return;
    }

    // Define regex patterns
    std::regex core_regex(R"(Core\d+:\s+(\d+)%?)");  // Matches "CoreX: YY%" where X is core number and YY is load
    std::regex total_regex(R"((\d+)%?)");           // Matches total load like "ZZ%"

    std::string line;
    bool total_found = false;

    // Iterate through each line in the file
    while (std::getline(file, line)) {
        std::smatch match;
        std::string::const_iterator searchStart(line.cbegin());

        // Search for all core loads in the current line
        while (std::regex_search(searchStart, line.cend(), match, core_regex)) {
            if (match.size() > 1) { // Ensure there's a capturing group
                try {
                    int load = std::stoi(match[1].str());
                    npuLoad.push_back(load);
                } catch (const std::invalid_argument& e) {
                    // Handle conversion error if necessary
                } catch (const std::out_of_range& e) {
                    // Handle out-of-range error if necessary
                }
            }
            // Move the search start position forward
            searchStart = match.suffix().first;
        }

        // If no cores were found in this line, try to find total load
        if (npuLoad.empty() && !total_found) {
            if (std::regex_search(line, match, total_regex)) {
                if (match.size() > 1) { // Ensure there's a capturing group
                    try {
                        int totalLoad = std::stoi(match[1].str());
                        npuLoad.push_back(totalLoad);
                        total_found = true; // Avoid multiple total entries
                    } catch (const std::invalid_argument& e) {
                        // Handle conversion error if necessary
                    } catch (const std::out_of_range& e) {
                        // Handle out-of-range error if necessary
                    }
                }
            }
        }
    }

    // Close the file
    file.close();

    // Update the number of NPUs based on the loaded data
    nrNPUs = npuLoad.size();
}

```

**Comment by heymikid** [comment]
You mean at the top? This was a while loop in bash (one per second) dumping the content of the rknpu/load file (which contained one line):

NPU load:  Core0: 58%, Core1:  0%, Core2:  0%,

while the program was running (on one NPU core out of the 3).
I don't understand where you would see 5 threads... Are you talking about the CPU or NPU?
The program runs on multi-processing (in python) doing a bunch of things, one process is using the NPU.

**Comment by heymikid** [comment]
Sorry to bother you with this. It seems to be a permission issue (I put this program in sudoers.d but I must have done it wrong). When running with sudo it gives the proper outout.
![Screenshot 2024-12-19 171555](https://github.com/user-attachments/assets/ef3ab540-4036-4182-8223-b25634a308e3)
The 54% and 53% are not from the exact same time.

Thanks for your help.

**Comment by benhoff** [comment]
No worries, glad it works!
